// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "07d05b52-8261-43e6-be33-3ce9b12f16dc");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1543967421);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1543967541);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1543970661);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1543967301);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1543967181);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1543967781);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1543967661);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b73464d1-695d-4a22-9463-2f5985ba9952}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543899600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1543967140);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1543970750466");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543972567466");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1543970655556");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543974255556");
user_pref("browser.search.countryCode", "PL");
user_pref("browser.search.region", "PL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1543967063");
user_pref("browser.startup.homepage_override.buildID", "20180712150008");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("extensions.blocklist.lastModified", "Mon, 26 Nov 2018 14:19:56 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1543967422);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"f4b31c70-9af6-4448-bf87-1728f633677c\",\"screenshots@mozilla.org\":\"ca617868-cfa1-47f1-bbb7-7e3ade21c3a3\"}");
user_pref("idle.lastDailyNotification", 1543970156);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1543967424);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180712150008");
user_pref("media.gmp-manager.lastCheck", 1543967607);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1543970156);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e6dcf61b-f567-46de-8e29-c6d1e6a2b1a6");
user_pref("services.blocklist.addons.checked", 1543952531);
user_pref("services.blocklist.gfx.checked", 1543952531);
user_pref("services.blocklist.onecrl.checked", 1543952531);
user_pref("services.blocklist.pinning.checked", 1543952531);
user_pref("services.blocklist.plugins.checked", 1543952531);
user_pref("services.settings.clock_skew_seconds", 15010);
user_pref("services.settings.last_etag", "\"1543241996691\"");
user_pref("services.settings.last_update_seconds", 1543952531);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1543970156);
user_pref("toolkit.startup.last_success", 1543967025);
user_pref("toolkit.telemetry.cachedClientID", "a396efa8-6b4d-4d21-8409-6726ef1766fe");
user_pref("toolkit.telemetry.previousBuildID", "20180712150008");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
